export type ThemeType = {
  primary: string;
  backgroundColor: string;
  statusBarColor: string;
  menuBackgroundColor: string;
  menuBorderColor: string;
  cardViewBackgroundColor: string;
  cardViewBorderColor: string;
  textColor: string;
  white: string;
  black: string;
  gray: string;
  languageIconBackgroundColor: string;
  activeTabTextColor: string;
  passiveTabTextColor: string;
  inputBackgroundColor: string;
  inputColor: string;
  segmentedControlBackgroundColor: string;
  segmentedControlSelectedBackgroundColor: string;
  segmentedControlTextColor: string;
};
