import {ThemeType} from '../models';

export const lightTheme: ThemeType = {
  primary: '#006667',
  backgroundColor: '#F2F2F7',
  statusBarColor: '#FFFFFF',
  menuBackgroundColor: '#FFFFFF',
  menuBorderColor: '#CCCCCC',
  cardViewBackgroundColor: '#FFFFFF',
  cardViewBorderColor: '#006667',
  textColor: '#000000',
  black: '#000',
  white: 'white',
  gray: '#CCCCCC',
  languageIconBackgroundColor: '#007AFF',
  activeTabTextColor: '#FFFFFF',
  passiveTabTextColor: '#9EAAB6',
  inputBackgroundColor: 'rgba(118, 118, 128, 0.12)',
  inputColor: 'rgba(60, 60, 67, 0.6)',
  segmentedControlTextColor: '#000000',
  segmentedControlBackgroundColor: 'rgba(118, 118, 128, 0.12)',
  segmentedControlSelectedBackgroundColor: '#FFFFFF',
  formErrorColor: '#FF3B30',
  infoIconColor: '#007AFF',
};

export const darkTheme: ThemeType = {
  primary: '#7BA697',
  backgroundColor: '#000000',
  statusBarColor: '#1C1C1E',
  menuBackgroundColor: '#1C1C1E',
  menuBorderColor: '#333333',
  cardViewBackgroundColor: '#1C1C1E',
  cardViewBorderColor: '#7BA697',
  textColor: '#FFFFFF',
  black: '#000',
  white: 'white',
  gray: '#CCCCCC',
  languageIconBackgroundColor: '#007AFF',
  activeTabTextColor: '#FFFFFF',
  passiveTabTextColor: '#9EAAB6',
  inputBackgroundColor: 'rgba(118, 118, 128, 0.24)',
  inputColor: 'rgba(235, 235, 245, 0.6)',
  segmentedControlTextColor: '#FFFFFF',
  segmentedControlBackgroundColor: '#313136',
  segmentedControlSelectedBackgroundColor: '#69696F',
  formErrorColor: '#FF453A',
  infoIconColor: '#0A84FF',
};
